import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid min-h-screen md:grid-cols-2">
      <div className="relative hidden md:block">
        <Image
          src="/assets/login.jpg"
          alt="Dogs"
          fill
          className="object-cover"
        />
      </div>
      <div>{children}</div>
    </div>
  );
}
